core/urls.py
from django.urls import path
from core.views import HomeView, QuestionDetailView, QuestionCreateView, QuestonDeleteView, QuestionUpdateView

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('questions/<int:pk>/', QuestionDetailView.as_view(), name='question-detail'),
    path('questions/<int:pk>/delete/', QuestonDeleteView.as_view(), name='question-delete'),
    path('questions/<int:pk>/update/', QuestionUpdateView.as_view(), name='question-update'),
    path('ask/', QuestionCreateView.as_view(), name='question-create')
]

stackoverflowClone1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('users.urls'))
]

users/urls.py
from django.urls import path
from users.views import CustomLoginView, CustomLogoutView, UserSignUpView

app_name = 'users'

urlpatterns = [
    path('sign-in/', CustomLoginView.as_view(), name='sign-in'),
    path('sign-out/', CustomLogoutView.as_view(), name='sign-out'),
    path('sign-up/', UserSignUpView.as_view(), name='sign-up'),
]

core/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError
    

# ORM

class Tag(models.Model):
    title = models.CharField(max_length=35, unique=True)
    
    def clean(self) -> None:
        if not self.title.islower():
            raise ValidationError({
                'title': 'Title should be only in lower case'
            })
    
    def __str__(self) -> str:
        return self.title


class Question(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)

    title = models.CharField(max_length=255)
    text = models.TextField()

    create_time = models.DateTimeField(auto_now_add=True)
    modify_time = models.DateTimeField(auto_now=True)

    views = models.PositiveIntegerField(default=0)

    def __str__(self) -> str:
        return f'{self.title}'
    




class Vote(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['user', 'question']


class Answer(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    text = models.TextField()

    create_time = models.DateTimeField(auto_now_add=True)
    modify_time = models.DateTimeField(auto_now=True)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class User(AbstractUser):
    pass

core/forms.py
from django import forms
from core.models import Question
from typing import Any

class QuestionCreateForm(forms.ModelForm):
    class Meta:
        model = Question
        # fields = '__all__'
        exclude = ['user', 'views']
    
    def __init__(self, *args, **kwargs) -> None:
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

    def save(self, commit: bool = ...) -> Any:
        question: Question = super().save(commit=False)
        question.user = self.user
        question.save()
        return question

users/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.password_validation import validate_password
from users.models import User

class UserCreateForm(forms.ModelForm):
    confirm_password = forms.CharField(widget=forms.widgets.PasswordInput(),
                                         validators=[validate_password])
    
    def clean(self):
        cleaned_data = super().clean()
        print(cleaned_data)
        if cleaned_data['confirm_password'] != cleaned_data['password']:
            raise ValidationError({
                'confirm_password': "Passwords don't match",
                'password': "Passwords don't match",
            })
        
        return cleaned_data

    class Meta:
        model = User
        fields = ['username', 'password', 'confirm_password']
        widgets = {
            'password': forms.PasswordInput(),
        }
    
    def save(self, commit: bool = False):
        user: User = super().save(False)
        user.set_password(user.password)
        user.save(commit)
        return user
    
            

core/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from core.models import Question
from core.forms import QuestionCreateForm
from django.urls import reverse_lazy, reverse
from typing import Dict, Any


def home_view(request: HttpRequest) -> HttpResponse:
    return render(request, 'home.html', context={
        'questions': Question.objects.all()
    })


class HomeView(ListView):
    template_name = 'home.html'
    context_object_name = 'questions'
    ordering = ['-create_time']
    paginate_by = 5

    def get_queryset(self):
        queryset = Question.objects.filter(title__contains=self.request.GET.get('q', ''))
    
        ordering = self.get_ordering()
        if ordering:
            if isinstance(ordering, str):
                ordering = (ordering,)
            queryset = queryset.order_by(*ordering)

        return queryset


class QuestionDetailView(DetailView):
    template_name = 'question_detail.html'
    model = Question


class QuestionCreateView(LoginRequiredMixin, CreateView):
    model = Question
    form_class = QuestionCreateForm
    template_name = 'question_create.html'
    success_url = reverse_lazy('core:home')

    def get_form_kwargs(self) -> Dict[str, Any]:
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        self.object.tags.add(
            *[tag.id for tag in form.cleaned_data['tags']]
        )
        return super().form_valid(form)
        


class QuestonDeleteView(LoginRequiredMixin, DeleteView):
    model = Question
    template_name = 'question_delete.html'
    success_url = reverse_lazy('core:home')

    def get_queryset(self):
        return Question.objects.filter(user=self.request.user)


class QuestionUpdateView(LoginRequiredMixin, UpdateView):
    model = Question
    template_name = 'question_update.html'
    fields = ['title', 'text']

    def get_success_url(self) -> str:
        return reverse('core:question-detail', kwargs={'pk': self.get_object().pk})

    def get_queryset(self):
        return Question.objects.filter(user=self.request.user)

users/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView
from django.urls import reverse_lazy
from users.forms import UserCreateForm

# Create your views here.
class CustomLoginView(LoginView):
    template_name = 'auth/sign_in.html'
    redirect_authenticated_user = True
    next_page = reverse_lazy('core:home')


class CustomLogoutView(LogoutView):
    next_page = reverse_lazy('core:home')


class UserSignUpView(CreateView):
    template_name = 'auth/sign_up.html'
    form_class = UserCreateForm
    success_url = reverse_lazy('core:home')
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=viewport, initial-scale=1.0">
    <title>Stackoverflow Clone</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>

    <link href="{% static 'main.css' %}" rel="stylesheet" /> 
</head>

{% comment %} <body style="background-image: url('{% static 'images/bg-image.jpg' %}')"> {% endcomment %}
<!-- This is a HTML comment -->
<body>
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'core:home' %}">Stackoverflow</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <form class="navbar-nav w-100 me-auto d-flex" role="search">
                    <input name="q" class="form-control me-2" type="search" placeholder="Search" aria-label="Search" value="{{ request.GET.q }}">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                <div class="btn-group">
                {% if not request.user.is_authenticated %}
                    <a href="{% url 'users:sign-in' %}" class="btn btn-primary">Sign In</a>
                    <a href="{% url 'users:sign-up' %}" class="btn btn-success">Sign Up</a>
                {% else %}
                    <span class="btn btn-primary disabled">{{ request.user.username }}</span>
                    <a href="{% url 'users:sign-out' %}" class="btn btn-danger">Sign Out</a>
                {% endif %}
                </div>
            </div>
        </div>
    </nav>

    <main class="container">
        {% block content %}
        
        {% endblock content %}
    </main>

</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Questions</h1>

<section class="bg-transparent p-3 rounded shadow-lg" style="backdrop-filter: blur(1rem)">
    <a href="{% url 'core:question-create' %}">Ask a new Question</a>
    {% for question in object_list %}
    <article class="border-top mt-3 border-secondary">
        <div class="row pt-3 pb-3">
            <div class="col-2 d-flex flex-column text-end">
                <span>{{ question.vote_set.all|length }} Votes</span>
                <span>{{ question.answer_set.all|length }} Answers</span>
                <span>{{ question.views }} Views</span>
            </div>
            <div class="col-10">
                <p><a href="{% url 'core:question-detail' question.pk %}">{{ question.title }}</a></p>
                <div class="d-flex flex-row justify-content-between"> 
                    <div>
                        {% for tag in question.tags.all %}
                        <div class="badge bg-primary">
                            {{ tag }}
                        </div>
                        {% endfor %}
                       
                    </div>
                    
                    <a href="#">
                        {{ question.user }} asked {{ question.create_time|timesince }} ago
                    </a>
                </div>
            </div>
        </div>
    </article>
    {% endfor %}
    <div class="pagination text-center justify-content-center">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" class="btn btn-primary">&#10094;&#10094;</a>
                <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" class="btn btn-primary">&#10094;</a>
            {% endif %}
    
            <span class="current btn btn-primary disabled">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" class="btn btn-primary">&#10095;</a>
                <a href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}" class="btn btn-primary">&#10095;&#10095;</a>
            {% endif %}
        </span>
    </div>
</section>
{% endblock content %}

templates/home_old.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=viewport, initial-scale=1.0">
    <title>Stackoverflow</title>
</head>

<body>
    <h1>Home</h1>

    {% for question in object_list %}
    <div>
        <ul>
            <li>{{ question.vote_set.all|length }} Vote</li>
            <li>{{ question.answer_set.all|length }} Answer</li>
            <li>{{ question.views }} Views</li>
        </ul>
        <a href="#">{{ question.title }}</a>
        <p>{{ question.text }}</p>
        <p>{{ question.user }}</p>
    </div>
    {% endfor %}
</body>

</html>

templates/question_create.html
{% extends 'base.html' %}

{% block content %}
<h1>Ask a Question</h1>
<section class="bg-transparent p-3 rounded shadow-lg" style="backdrop-filter: blur(1rem)">
    <form method='POST'>
        {% csrf_token %}
        {{ form.as_p }}

        <button class='btn btn-primary'>Ask</button>
    </form>
</section>

{% endblock content %}

templates/question_delete.html
{% extends 'base.html' %}

{% block content %}

<form method='POST'>
    {% csrf_token %}

    <button class="btn btn-danger">Confirm</button>
    <a href="{% url 'core:question-detail' question.pk %}" class="btn btn-primary">Go Back</a>
</form>
{% endblock content %}

templates/question_detail.html
{% extends 'base.html' %}

{% block content %}

{% if question.user == request.user %}
    <a href="{% url 'core:question-delete' question.pk %}" class='btn btn-danger'>Delete</a>
    <a href="{% url 'core:question-update' question.pk %}" class='btn btn-primary'>Edit</a>
{% endif %}

<h2>{{ question.title }}</h2>
<p>{{ question.text }}</p>
{% endblock content %}

templates/question_update.html
{% extends 'base.html' %}

{% block content %}

<form method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    
    <button class="btn btn-success">Confirm</button>
    <a href="{% url 'core:question-detail' question.pk %}" class="btn btn-primary">Go Back</a>
</form>
{% endblock content %}